---
title: "Analisis de Secuencias"
author: "Maria Fernanda Zuñiga Gonzalez"
date: "30/11/2020"
output: html_document
---
```{r}
library(sangerseqR)
library(sangeranalyseR)
library(tidyverse)
library(ggrepel) #Ggplot2 labels
library(RColorBrewer)
library(readxl)
library(FactoMineR)
library(factoextra)
library(vegan)
```

```{r}
example1 <- readsangerseq('daniados/17R_12SF1MT.ab1')
```

```{r}
contigName <- "17R_12S"
suffixForwardRegExp <- "_12SF1MT.ab1$"
suffixReverseRegExp <- "_12SR1MT.ab1$"

sangerContig <- SangerContig(parentDirectory = 'daniados/', suffixForwardRegExp = suffixForwardRegExp, suffixReverseRegExp = suffixReverseRegExp)

writeFastaSC(sangerContig, outputDir = '.')
```

```{r}
sangerAlignment <- 
        SangerAlignment(parentDirectory = 'daniados/',
                        suffixForwardRegExp = suffixForwardRegExp,
                        suffixReverseRegExp = suffixReverseRegExp,)
writeFastaSA(sangerAlignment, outputDir = '.')
```

## Analisis estadistico de la base de datos

```{r}
df <- read_xlsx('MT_base_final.xlsx', sheet = 1, na = 'NA') %>%
    mutate(sitio_cat = recode(Sitio_de_colecta, `Belgrado (Maní)`='Mani', `Cruz Verde (Tamara)`='Tamara', `Cueva guacharos (Aguazul)`='Aguazul', `Curama (Pore)`='Pore', `La Graciela (Aguazul)`='Aguazul', `La niata (Yopal)`='Yopal', `Ramon Nonato (Pore)`='Pore', `San Isidro (Pore)`='Pore'))

df_MCA <- df %>%
    filter(Organismos == 'Murcielago', Infeccion != 'Ninguno', Especie_12S != 'Chiroptera') 

nombresMuestras <- df_MCA$`Nombre muestra`
infeccion <- df_MCA$Infeccion
especies <- df_MCA$Especie_12S

df_dieta <- df_MCA[c(13:16)] %>%
    summarise_if(is.numeric, sum, na.rm = TRUE) %>% 
    pivot_longer(cols = everything(), names_to = 'Dieta', values_to = 'Cantidad')

df_dieta_long <- df_MCA[c(11, 13:16)] %>%
    pivot_longer(cols = Insectivoro:Carnivoro, names_to = "Dieta") %>%
    filter(value != 0) %>%
    group_by(Especie_12S, Dieta) %>%
    count(name = 'Cantidad')
    
df_habitat <- df_MCA[c(17:20)] %>%
    summarise_if(is.numeric, sum, na.rm = TRUE) %>% 
    pivot_longer(cols = everything(), names_to = 'Habitat', values_to = 'Cantidad')

df_habitat_long <- df_MCA[c(11, 17:20)] %>%
    pivot_longer(cols = Silvestre:Urban_no_habitado, names_to = "Habitat") %>%
    filter(value != 0) %>%
    group_by(Especie_12S, Habitat) %>%
    count(name = 'Cantidad')

df_MCA$Sitio_de_colecta <- as.factor(df_MCA$Sitio_de_colecta)
df_MCA$Especie_12S <- as.factor(df_MCA$Especie_12S)
df_MCA$Insectivoro <- as.factor(df_MCA$Insectivoro)
df_MCA$Nectarivoro <- as.factor(df_MCA$Nectarivoro)
df_MCA$Fructifero <- as.factor(df_MCA$Fructifero)
df_MCA$Carnivoro <- as.factor(df_MCA$Carnivoro)
df_MCA$Silvestre <- as.factor(df_MCA$Silvestre)
df_MCA$Rural <- as.factor(df_MCA$Rural)
df_MCA$Urbano <- as.factor(df_MCA$Urbano)
df_MCA$Urban_no_habitado <- as.factor(df_MCA$Urban_no_habitado)

# Seleccionar columnas Sitio, Especie_12S y Habitos
# df_MCA <- df_MCA[c(5, 13:20)]

```

```{r}
ggplot(df_dieta, aes(x = Dieta, y = Cantidad, fill = Dieta)) + 
    geom_bar(stat = 'identity') + 
    scale_fill_brewer(type = 'qual', palette = 1) +
    theme_classic()
```
```{r}
ggplot(df_habitat, aes(x = Habitat, y = Cantidad, fill = Habitat)) + 
    geom_bar(stat = 'identity') + 
    scale_fill_brewer(type = 'qual', palette = 2) +
    theme_classic()
```

```{r}
res.mca <- MCA(df_MCA[c(5, 13:20)], graph = FALSE)
df_MCA_dim <- as.data.frame(get_mca_ind(res.mca = res.mca)$coord)
df_MCA_dim$nombresMuestras <- nombresMuestras
df_MCA_dim$infeccion <- infeccion
df_MCA_dim$especies <- especies
```

```{r}
eig.val <- get_eigenvalue(res.mca)
fviz_screeplot(res.mca, addlabels = TRUE, ylim = c(0, 45), ggtheme = theme_classic())
```

```{r}
fviz_mca_biplot(res.mca, repel = TRUE, ggtheme = theme_classic())
```
```{r}
fviz_mca_var(res.mca, choice = "mca.cor", 
            repel = TRUE, # Avoid text overlapping (slow)
            ggtheme = theme_classic())
```

```{r}
ggplot(df_MCA_dim, aes(x = `Dim 1`, y = `Dim 2`, color = especies, shape = infeccion, label = nombresMuestras)) + 
    geom_point(alpha = 0.5, size = 5) +
    geom_text_repel(force = 5, size = 5, show.legend = F) +
    scale_color_manual(values = c('#e41a1c', '#377eb8', '#4daf4a', '#984ea3', '#ff7f00', '#959c17', '#a65628', '#f781bf', '#999999')) +
    labs(x = 'Dim 1 (33.2%)', y = 'Dim 2 (17.3%)', color = 'Especie', shape = 'Parásito(s)') +
    theme_classic() +
    theme(axis.title = element_text(face = 'bold', size = 20),
          axis.text = element_text(size = 15),
          legend.title = element_text(face = 'bold', size = 15),
          legend.text = element_text(face = 'italic', size = 13),
          legend.position = 'bottom')
```

```{r}
ggplot(df %>% filter(Organismos == 'Murcielago', Infeccion != 'Ninguno'), aes(y = Especie_12S, fill = Infeccion)) +
    geom_bar(stat = 'count', position = position_dodge()) +
    scale_x_continuous(breaks = seq(0, 14, 2)) +
    scale_fill_brewer(type = 'qual',palette = 'Pastel1') +
    labs(x = 'Cantidad', y = 'Especie', fill = 'Parásito(s)') +
    facet_wrap(~Sitio_de_colecta, nrow = 2, scales = 'free_y') +
    theme_classic() +
    theme(axis.title = element_text(face = 'bold', size = 20),
          axis.text = element_text(size = 15, hjust = 0),
          axis.text.y = element_text(face = 'italic'),
          strip.text = element_text(face = 'bold', size = 13),
          strip.background = element_blank(),
          legend.title = element_text(face = 'bold', size = 15),
          legend.text = element_text(face = 'italic', size = 13),
          legend.position = 'bottom')
```

```{r}
ggplot(df %>% filter(Organismos == 'Murcielago', Infeccion != 'Ninguno'), aes(y = Especie_12S, fill = Infeccion)) +
    geom_bar(stat = 'count', position = position_dodge()) +
    scale_x_continuous(breaks = seq(0, 14, 2)) +
    scale_fill_brewer(type = 'qual',palette = 'Pastel1') +
    labs(x = 'Cantidad', y = 'Especie', fill = 'Parásito(s)') +
    facet_wrap(~sitio_cat, nrow = 2, scales = 'free_y') +
    theme_classic() +
    theme(axis.title = element_text(face = 'bold', size = 20),
          axis.text = element_text(size = 15, hjust = 0),
          axis.text.y = element_text(face = 'italic'),
          strip.text = element_text(face = 'bold', size = 13),
          strip.background = element_blank(),
          legend.title = element_text(face = 'bold', size = 15),
          legend.text = element_text(face = 'italic', size = 13),
          legend.position = 'bottom')
```


```{r}
brewerpalette <- colorRampPalette(brewer.pal(24, 'PuBu'))

ggplot(df_dieta_long, aes(x = Dieta, y = Especie_12S, fill = Cantidad)) + 
    geom_tile() + 
    geom_text(aes(label = Cantidad), size = 7) +
    coord_equal() +
    theme(panel.grid = element_blank(),
          panel.background = element_blank(),
          plot.title = element_text(size = 20, hjust = 0.5, face = 'bold'),
          panel.border = element_rect(color = 'black', fill = NA),
          axis.text.y = element_text(face = 'italic', size = 15),
          axis.text.x = element_text(angle = -25, size = 15, hjust = 0),
          axis.title = element_blank(),
          strip.text = element_text(size = 15),
          strip.background = element_blank(),
          legend.title = element_text(size = 15, vjust = 1),
          legend.position = 'bottom') +
    scale_fill_gradientn(colours = brewerpalette(20), name = 'Cantidad', breaks = as.integer)
```


```{r}
brewerpalette <- colorRampPalette(brewer.pal(24, 'Greens'))

ggplot(df_habitat_long, aes(x = Habitat, y = Especie_12S, fill = Cantidad)) + 
    geom_tile() + 
    geom_text(aes(label = Cantidad), size = 7) +
    coord_equal() +
    theme(panel.grid = element_blank(),
          panel.background = element_blank(),
          plot.title = element_text(size = 20, hjust = 0.5, face = 'bold'),
          panel.border = element_rect(color = 'black', fill = NA),
          axis.text.y = element_text(face = 'italic', size = 15),
          axis.text.x = element_text(angle = -25, size = 15, hjust = 0),
          axis.title = element_blank(),
          strip.text = element_text(size = 15),
          strip.background = element_blank(),
          legend.title = element_text(size = 15, vjust = 1),
          legend.position = 'bottom') +
    scale_fill_gradientn(colours = brewerpalette(20), name = 'Cantidad', breaks = as.integer)
```

## Analisis de Diversidad
```{r}
df_conteo <- df_MCA %>%
    select(Sitio_de_colecta, Especie_12S) %>%
    group_by(Sitio_de_colecta, Especie_12S) %>%
    count(name = 'Conteo', ) %>%
    pivot_wider(names_from = Especie_12S, values_from = Conteo) %>%
    replace_na(list(`Myotis brandtii` = 0, `Carollia perspicillata` = 0, `Glossophaga soricina` = 0, `Micronycteris brachyotis` = 0, `Anoura caudifer` = 0, `Phyllostomus hastatus` = 0, `Saccopteryx leptura` = 0, `Carollia brevicauda` = 0, `Vampyrum spectrum` = 0))

alfa1 <- diversity(df_conteo[-1], index = 'shannon')
beta1 <- betadiver(df_conteo[-1], method = 1)
```

```{r}
data_frame(Sitio_de_colecta = df_conteo$Sitio_de_colecta, alfa = alfa1) %>%
ggplot(aes(y = Sitio_de_colecta, x = alfa1, fill = Sitio_de_colecta)) +
    geom_bar(stat = 'identity') + 
    scale_fill_brewer(type = 'qual', palette = 4) +
    labs(y = 'Sitio de Colecta', fill = 'Sitio de Colecta', x = 'Diversidad Alfa (Shannon)') +
    theme_classic()
```


```{r}
df_conteo2 <- df_MCA %>%
    mutate(sitio_cat = recode(Sitio_de_colecta, `Belgrado (Maní)`='Mani', `Cruz Verde (Tamara)`='Tamara', `Cueva guacharos (Aguazul)`='Aguazul', `Curama (pore)`='Pore', `La Graciela (Aguazul)`='Aguazul', `La niata (yopal)`='Yopal', `Ramon Nonato (Pore)`='Pore', `San Isidro (Pore)`='Pore')) %>%
    select(sitio_cat, Especie_12S) %>%
    group_by(sitio_cat, Especie_12S) %>%
    count(name = 'Conteo') %>%
    pivot_wider(names_from = Especie_12S, values_from = Conteo) %>%
    replace_na(list(`Myotis brandtii` = 0, `Carollia perspicillata` = 0, `Glossophaga soricina` = 0, `Micronycteris brachyotis` = 0, `Anoura caudifer` = 0, `Phyllostomus hastatus` = 0, `Saccopteryx leptura` = 0, `Carollia brevicauda` = 0, `Vampyrum spectrum` = 0))

alfa2 <- diversity(df_conteo2[-1], index = 'shannon')
beta2 <- betadiver(df_conteo2[-1], )
```

```{r}
data_frame(sitio_cat = df_conteo2$sitio_cat, alfa = alfa2) %>%
ggplot(aes(y = sitio_cat, x = alfa2, fill = sitio_cat)) +
    geom_bar(stat = 'identity') + 
    scale_fill_brewer(type = 'qual', palette = 5) +
    labs(y = 'Municipio', fill = 'Municipio', x = 'Diversidad Alfa (Shannon)') +
    theme_classic()
```